# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
android.enableJetifier=true
android.useAndroidX=true
android.jetifier.ignorelist=org.bouncycastle:bcpkix-jdk18on, \
  org.bouncycastle:bcprov-jdk18on, \
  org.bouncycastle:bcutil-jdk18on, \
  org.robolectric:annotations, \
  org.robolectric:junit, \
  org.robolectric:nativeruntime, \
  org.robolectric:pluginapi, \
  org.robolectric:plugins-maven-dependency-resolver, \
  org.robolectric:resource, \
  org.robolectric:robolectric, \
  org.robolectric:sandbox, \
  org.robolectric:shadowapi, \
  org.robolectric:shadows-framework, \
  org.robolectric:shadows-httpclient, \
  org.robolectric:utils, \
  org.robolectric:utils-reflector, \
  org.slf4j:slf4j-api, \
  net.lingala.zip4j:zip4j, \
  org.tukaani:xz, \
  org.jsoup:jsoup, \
  org.hamcrest:hamcrest, \
  org.hamcrest:hamcrest-core, \
  org.hamcrest:hamcrest-library, \
  org.awaitility:awaitility, \
  org.mockito:mockito-core, \
  org.mockito:mockito-inline, \
  io.mockk:mockk, \
  eu.agno3.jcifs:jcifs-ng, \
  commons-codec:commons-codec, \
  commons-net:commons-net, \
  commons-io:commons-io, \
  commons-logging:commons-logging, \
  com.google.guava:guava, \
  com.google.guava:listenablefuture, \
  com.github.npgall:concurrent-trees, \
  com.hierynomus:sshj, \
  com.ibm.icu:icu4j, \
  com.google.code.gson:gson, \
  com.google.guava:guava, \
  com.google.guava:listenablefuture, \
  ch.qos.logback:logback-core, \
  ch.qos.logback:logback-classic, \
  com.almworks.sqlite4java:sqlite4java, \
  org.apache.ftpserver:ftpserver, \
  com.github.topjohnwu.libsu:core, \
  com.github.topjohnwu.libsu:io, \
  org.apache.mina:mina-core, \
  org.apache.sshd:sshd-core, \
  org.apache.sshd:sshd-scp, \
  org.apache.sshd:sshd-sftp, \
  junit:junit

org.gradle.jvmargs=-Xmx4608M -XX:+UseParallelGC \
  --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
  --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
org.gradle.parallel=true

# https://github.com/usefulness/easylauncher-gradle-plugin/issues/408
android.disableResourceValidation=true
# for macs, omit for other operating systems
# org.gradle.java.home=/Applications/Android Studio.app/Contents/jbr/Contents/Home

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
