package com.amaze.filemanager.database.daos;

import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.amaze.filemanager.database.models.utilities.Bookmark;

import static com.amaze.filemanager.database.UtilitiesDatabase.COLUMN_NAME;
import static com.amaze.filemanager.database.UtilitiesDatabase.COLUMN_PATH;
import static com.amaze.filemanager.database.UtilitiesDatabase.TABLE_BOOKMARKS;

/**
 * {@link Dao} interface definition for {@link Bookmark}. Concrete class is generated by Room
 * during build.
 *
 * @see Dao
 * @see Bookmark
 * @see com.amaze.filemanager.database.UtilitiesDatabase
 */
@Dao
public interface BookmarkEntryDao {

    @Insert
    public void insert(Bookmark instance);

    @Update
    public void update(Bookmark instance);

    @Query("SELECT * FROM " + TABLE_BOOKMARKS)
    public Bookmark[] list();

    @Query("SELECT * FROM " + TABLE_BOOKMARKS + " WHERE " + COLUMN_NAME + " = :name AND " + COLUMN_PATH + " = :path")
    public Bookmark findByNameAndPath(String name, String path);

    @Query("DELETE FROM " + TABLE_BOOKMARKS + " WHERE " + COLUMN_NAME + " = :name AND " + COLUMN_PATH + " = :path")
    public void deleteByNameAndPath(String name, String path);
}
