/*
 * Copyright (C) 2014-2023 Arpit Khurana <arpitkh96@gmail.com>, Vishal Nehra <vishalmeham2@gmail.com>,
 * Emmanuel Messulam<emmanuelbendavid@gmail.com>, Raymond Lai <airwave209gt at gmail.com> and Contributors.
 *
 * This file is part of Amaze File Manager.
 *
 * Amaze File Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.amaze.filemanager.database.daos

import androidx.room.*
import com.amaze.filemanager.database.models.explorer.EncryptedEntry
import io.reactivex.Completable
import com.amaze.filemanager.database.ExplorerDatabase
import io.reactivex.Single

/**
 * [Dao] interface definition for [EncryptedEntry]. Concrete class is generated by Room
 * during build.
 *
 * @see Dao
 *
 * @see EncryptedEntry
 *
 * @see com.amaze.filemanager.database.ExplorerDatabase
 */
@Dao
interface EncryptedEntryDao {

    @Insert
    fun insert(entry: EncryptedEntry): Completable

    @Query("SELECT * FROM " + ExplorerDatabase.TABLE_ENCRYPTED + " WHERE " + ExplorerDatabase.COLUMN_PATH + " = :path")
    fun select(path: String): Single<EncryptedEntry?>

    @Update
    fun update(entry: EncryptedEntry): Completable

    @Transaction
    @Query("DELETE FROM " + ExplorerDatabase.TABLE_ENCRYPTED + " WHERE " + ExplorerDatabase.COLUMN_PATH + " = :path")
    fun delete(path: String): Completable

    @Query("SELECT * FROM " + ExplorerDatabase.TABLE_ENCRYPTED)
    fun list(): Single<List<EncryptedEntry>>

}