/*
 * Copyright (C) 2014-2023 Arpit Khurana <arpitkh96@gmail.com>, Vishal Nehra <vishalmeham2@gmail.com>,
 * Emmanuel Messulam<emmanuelbendavid@gmail.com>, Raymond Lai <airwave209gt at gmail.com> and Contributors.
 *
 * This file is part of Amaze File Manager.
 *
 * Amaze File Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.amaze.filemanager.database.daos

import androidx.room.*
import com.amaze.filemanager.database.ExplorerDatabase
import com.amaze.filemanager.database.models.explorer.Sort
import io.reactivex.Completable
import io.reactivex.Single

/**
 * [Dao] interface definition for [Sort]. Concrete class is generated by Room during
 * build.
 *
 * @see Dao
 *
 * @see Sort
 *
 * @see com.amaze.filemanager.database.ExplorerDatabase
 */
@Dao
interface SortDao {

    @Insert
    fun insert(entity: Sort): Completable

    @Query(
        "SELECT * FROM " +
            ExplorerDatabase.TABLE_SORT +
            " WHERE " +
            ExplorerDatabase.COLUMN_PATH +
            " = :path"
    )
    fun find(path: String?): Single<Sort?>

    @Transaction
    @Query(
        "DELETE FROM " +
            ExplorerDatabase.TABLE_SORT +
            " WHERE " +
            ExplorerDatabase.COLUMN_PATH +
            " = :path"
    )
    fun clear(path: String?): Completable

    @Update
    fun update(entity: Sort?): Completable
}
