name: Android Build CI

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release/*'
concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check_spotless:
    name: Check spotless
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: Check formatting using spotless
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: spotlessCheck --stacktrace

  build:
    name: Build debug
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 11
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: assembledebug --stacktrace