name: Fastlane checks

on:
  pull_request:
    branches:
      - 'master'
      - 'release/*'
      - 'hotfix/*'

jobs:
  check_files:
    name: Check Fastlane with canned action
    # required to run on Linux because this is a docker container action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
        with:
          fastlaneDir: ./fastlane/metadata/android # optional
          usePlayStoreLocales: true # optional
