name: TranceLove fix Github CI action

on:
  push:
    branches:
      - 'TranceLove/github-ci-fix'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build debug, Jacoco test and publish to codacy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
          cache: 'gradle'
      - name: Build with Gradle
        run: |
          ./gradlew assembledebug
      - name: Run test cases
        run: ./gradlew jacocoTestPlayDebugUnitTestReport
  test_emulator:
    timeout-minutes: 30 # Emulator can get stuck
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [16, 19, 28]
        target: [default, google_apis]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${ { runner.os } }-${ { hashFiles('**/*.gradle*') } }-${ { hashFiles('**/gradle/wrapper/gradle-wrapper.properties') } }-${ { hashFiles('**/buildSrc/**/*.kt') } }
      - uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
            ~/.android/debug.keystore
          key: avd-${ { matrix.api-level } }
      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${ { matrix.api-level } }
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          sdcard-path-or-size: 100M
          arch: x86_64
          ram-size: 2048M
          channel: canary
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${ { matrix.api-level } }
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          sdcard-path-or-size: 100M
          arch: x86_64
          ram-size: 2048M
          channel: canary
          script: |
            adb logcat -c
            adb logcat *:E &
            ./gradlew :app:connectedCheck
