name: Publish Test Results

on:
  workflow_run:
    workflows: ["Android Build CI", "Android Feature CI"]
    types:
      - completed
permissions: {}

jobs:
  publish_test_results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'

    permissions:
      checks: write
      pull-requests: write
      actions: read
    steps:
      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
         run_id: ${{ github.event.workflow_run.id }}
         path: artifacts
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.16.1
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/*.xml"
